### ISSUE TITLE
Spostamento step

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/docs#5]
Il seguente step "Nel caso in cui la batteria sia completamente scarica, il display nella parte inferiore di CoderBot, accessibile capovolgendolo, inizierà a lampeggiare visualizzando uno 0. In questo caso, dovrai ricaricare la batteria prima di continuare. Altrimenti, il display visualizza la percentuale di carica rimanente.” lo sposterei come primo step della parte sulla ricarica della batteria.

**Comment by avivace** [comment]
Ora il paragrafo inizia così. Accensione -> controllare se è scarico -> Ricaricare la batteria.
