### ISSUE TITLE
Documentazione singoli comandi blockly

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/docs#9]
In una ottica di documentazione ogni comando Blockly dovrebbe essere brevemente spiegato. Alcuni comandi sono di utilizzo tutt’altro che ovvio perché ritornano oggetti complessi. Per fare un esempio quello che legge un AR code non ritorna un numero ma una lista di valori.

**Comment by avivace** [comment]
Sono d'accordo, anche se la questione del blocco per i codici AR andrebbe semplificata prima di pensare alla sua documentazione (vedi https://github.com/CoderBotOrg/vue-app/issues/47)

**Comment by previ** [comment]
Ora i blocchi sono (almeno parzialmente) [documentati qui](https://docs.coderbot.org/usermanual/blocks/).
Manca la documentazione dei blocchi "standard", che purtroppo in Blockly è assente, pur essendo i blocchi appunto "standard".
